version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: Main data for analysis
    tables: 
    - name: sales
      identifier: raw_gz_sales
      description: sales table
      
    - name: products
      identifier: raw_gz_product
      description: products table
    - name: ship
      identifier: raw_gz_ship
      description: ship_table
     